In [ ]:
import pandas as pd

# Path to the CSVs generated by sn-trackeval
df_baseline = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\baseline\pedestrian_summary.txt", sep=r'\s+').T
df_gta = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_gta\pedestrian_summary.txt", sep=r'\s+').T
df_xgb = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_xgb\pedestrian_summary.txt", sep=r'\s+').T
df_soccer = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_simple_merge_jersey\pedestrian_summary.txt", sep=r'\s+').T
df_soccer_jersey_team = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_simple_merge_jersey_team\pedestrian_summary.txt", sep=r'\s+').T
df_soccer_jersey_team_traj = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_simple_merge_jersey_team_traj\pedestrian_summary.txt", sep=r'\s+').T
df_soccer_jersey_team_traj_bbox = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_simple_merge_jersey_team_traj_bbox\pedestrian_summary.txt", sep=r'\s+').T


# Create a comparison table for your thesis
comparison = pd.concat([df_baseline, df_gta, df_xgb, df_soccer, df_soccer_jersey_team, df_soccer_jersey_team_traj, df_soccer_jersey_team_traj_bbox], axis=1)
comparison.columns = ['baseline', 'GTA', 'XGBoost Merger', 'SoccerAware_jersey', 'SoccerAware_jersey_team', 'df_soccer_jersey_team_traj', 'df_soccer_jersey_team_traj_bbox']

critical_metrics = ['HOTA', 'AssA', 'DetA', 'MOTA', 'IDF1', 'IDSW', 'IDTP', 'IDFP' , 'IDs', 'GT_IDs']
final_view = comparison.loc[critical_metrics]

final_view

,baseline,GTA,XGBoost Merger,SoccerAware_jersey,SoccerAware_jersey_team,df_soccer_jersey_team_traj,df_soccer_jersey_team_traj_bbox
HOTA,74.517,81.821,77.808,80.795,81.259,79.495,78.608
AssA,71.461,67.807,66.469,66.225,66.928,64.129,62.651
DetA,77.704,98.732,91.081,98.572,98.660,98.542,98.628
MOTA,71.910,99.257,90.730,99.027,98.889,98.743,98.708
IDF1,73.236,78.940,75.837,77.798,78.079,76.028,74.869
IDSW,2628.000,2620.000,2742.000,2854.000,3162.000,3529.000,3592.000
IDTP,431706.000,409415.000,409458.000,403277.000,404851.000,394366.000,388396.000
IDFP,229196.000,109824.000,152339.000,115419.000,114144.000,125024.000,131108.000
IDs,2086.000,1058.000,1376.000,1092.000,1130.000,1173.000,1180.000
GT_IDs,1116.000,1116.000,1116.000,1116.000,1116.000,1116.000,1116.000

:

In [1]:
import pandas as pd

# Path to the CSVs generated by sn-trackeval
df_baseline = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\baseline\pedestrian_summary.txt", sep=r'\s+').T
df_gta = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_gta\pedestrian_summary.txt", sep=r'\s+').T
df_xgb = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_xgb\pedestrian_summary.txt", sep=r'\s+').T
df_soccer = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_simple_merge_jersey\pedestrian_summary.txt", sep=r'\s+').T
df_soccer_jersey_team = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_simple_merge_jersey_team\pedestrian_summary.txt", sep=r'\s+').T
df_soccer_jersey_team_traj = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_simple_merge_jersey_team_traj\pedestrian_summary.txt", sep=r'\s+').T
df_soccer_jersey_team_traj_bbox = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_simple_merge_jersey_team_traj_bbox\pedestrian_summary.txt", sep=r'\s+').T


# Create a comparison table for your thesis
comparison = pd.concat([df_baseline, df_gta, df_xgb, df_soccer, df_soccer_jersey_team, df_soccer_jersey_team_traj, df_soccer_jersey_team_traj_bbox], axis=1)
comparison.columns = ['baseline', 'GTA', 'XGBoost Merger', 'SoccerAware_jersey', 'SoccerAware_jersey_team', 'df_soccer_jersey_team_traj', 'df_soccer_jersey_team_traj_bbox']

critical_metrics = ['HOTA', 'AssA', 'DetA', 'MOTA', 'IDF1', 'IDSW', 'IDTP', 'IDFP' , 'IDs', 'GT_IDs']
final_view = comparison.loc[critical_metrics]

final_view

,baseline,GTA,XGBoost Merger,SoccerAware_jersey,SoccerAware_jersey_team,df_soccer_jersey_team_traj,df_soccer_jersey_team_traj_bbox
HOTA,74.517,81.821,77.808,80.795,81.259,79.495,81.259
AssA,71.461,67.807,66.469,66.225,66.928,64.129,66.928
DetA,77.704,98.732,91.081,98.572,98.660,98.542,98.660
MOTA,71.910,99.257,90.730,99.027,98.889,98.743,98.889
IDF1,73.236,78.940,75.837,77.798,78.079,76.028,78.079
IDSW,2628.000,2620.000,2742.000,2854.000,3162.000,3529.000,3162.000
IDTP,431706.000,409415.000,409458.000,403277.000,404851.000,394366.000,404851.000
IDFP,229196.000,109824.000,152339.000,115419.000,114144.000,125024.000,114144.000
IDs,2086.000,1058.000,1376.000,1092.000,1130.000,1173.000,1130.000
GT_IDs,1116.000,1116.000,1116.000,1116.000,1116.000,1116.000,1116.000

In [2]:
import pandas as pd

# Path to the CSVs generated by sn-trackeval
df_baseline = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\baseline\pedestrian_summary.txt", sep=r'\s+').T
df_gta = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_gta\pedestrian_summary.txt", sep=r'\s+').T
df_xgb = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_xgb\pedestrian_summary.txt", sep=r'\s+').T
df_soccer = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_simple_merge_jersey\pedestrian_summary.txt", sep=r'\s+').T
df_soccer_jersey_team = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_simple_merge_jersey_team\pedestrian_summary.txt", sep=r'\s+').T
df_soccer_jersey_team_traj = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_simple_merge_jersey_team_traj\pedestrian_summary.txt", sep=r'\s+').T
df_soccer_jersey_team_traj_bbox = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_simple_merge_jersey_team_traj_bbox\pedestrian_summary.txt", sep=r'\s+').T


# Create a comparison table for your thesis
comparison = pd.concat([df_baseline, df_gta, df_xgb, df_soccer, df_soccer_jersey_team, df_soccer_jersey_team_traj, df_soccer_jersey_team_traj_bbox], axis=1)
comparison.columns = ['baseline', 'GTA', 'XGBoost Merger', 'SoccerAware_jersey', 'SoccerAware_jersey_team', 'df_soccer_jersey_team_traj', 'df_soccer_jersey_team_traj_bbox']

critical_metrics = ['HOTA', 'AssA', 'DetA', 'MOTA', 'IDF1', 'IDSW', 'IDTP', 'IDFP' , 'IDs', 'GT_IDs']
final_view = comparison.loc[critical_metrics]

final_view

,baseline,GTA,XGBoost Merger,SoccerAware_jersey,SoccerAware_jersey_team,df_soccer_jersey_team_traj,df_soccer_jersey_team_traj_bbox
HOTA,74.517,81.821,77.808,80.795,81.259,79.495,80.294
AssA,71.461,67.807,66.469,66.225,66.928,64.129,65.335
DetA,77.704,98.732,91.081,98.572,98.660,98.542,98.678
MOTA,71.910,99.257,90.730,99.027,98.889,98.743,98.885
IDF1,73.236,78.940,75.837,77.798,78.079,76.028,76.980
IDSW,2628.000,2620.000,2742.000,2854.000,3162.000,3529.000,3184.000
IDTP,431706.000,409415.000,409458.000,403277.000,404851.000,394366.000,399152.000
IDFP,229196.000,109824.000,152339.000,115419.000,114144.000,125024.000,119843.000
IDs,2086.000,1058.000,1376.000,1092.000,1130.000,1173.000,1135.000
GT_IDs,1116.000,1116.000,1116.000,1116.000,1116.000,1116.000,1116.000

In [24]:
import pandas as pd

# Path to the CSVs generated by sn-trackeval
df_baseline = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\baseline\pedestrian_summary.txt", sep=r'\s+').T
df_gta = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_gta\pedestrian_summary.txt", sep=r'\s+').T
df_test = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\testing_gta\pedestrian_summary.txt", sep=r'\s+').T


# Create a comparison table for your thesis
comparison = pd.concat([df_baseline, df_gta, df_test], axis=1)
comparison.columns = ['baseline', 'GTA', 'df_test']

critical_metrics = ['HOTA', 'AssA', 'DetA', 'MOTA', 'IDF1', 'IDSW', 'IDTP', 'IDFP' , 'IDs', 'GT_IDs']
final_view = comparison.loc[critical_metrics]

final_view

          baseline         GTA     df_test
HOTA        74.517      81.821      82.721
AssA        71.461      67.807      69.204
DetA        77.704      98.732      98.878
MOTA        71.910      99.257      99.221
IDF1        73.236      78.940      78.395
IDSW      2628.000    2620.000    2809.000
IDTP    431706.000  409415.000  406584.000
IDFP    229196.000  109824.000  112655.000
IDs       2086.000    1058.000    2086.000
GT_IDs    1116.000    1116.000    1116.000

In [26]:
import pandas as pd

# Path to the CSVs generated by sn-trackeval
df_baseline = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\baseline\pedestrian_summary.txt", sep=r'\s+').T
df_gta = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_gta\pedestrian_summary.txt", sep=r'\s+').T
df_xgb = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_xgb\pedestrian_summary.txt", sep=r'\s+').T
df_simple = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\evaluation\trackers\after_simple_merge\pedestrian_summary.txt", sep=r'\s+').T


# Create a comparison table for your thesis
comparison = pd.concat([df_baseline, df_gta, df_xgb, df_simple], axis=1)
comparison.columns = ['df_baseline', 'df_gta', 'df_xgb', 'df_simple']

critical_metrics = ['HOTA', 'AssA', 'DetA', 'MOTA', 'IDF1', 'IDSW', 'IDTP', 'IDFP' , 'IDs', 'GT_IDs']
final_view = comparison.loc[critical_metrics]

final_view

        df_baseline      df_gta      df_xgb   df_simple
HOTA         82.721      81.821      82.108      82.457
AssA         69.204      67.807      68.219      68.882
DetA         98.878      98.732      98.826      98.709
MOTA         99.221      99.257      99.277      99.261
IDF1         78.395      78.940      79.496      79.640
IDSW       2809.000    2620.000    2515.000    2601.000
IDTP     406584.000  409415.000  412295.000  413041.000
IDFP     112655.000  109824.000  106944.000  106198.000
IDs        2086.000    1058.000    1253.000    1054.000
GT_IDs     1116.000    1116.000    1116.000    1116.000