# Evaluate each splitter on the baseline

In [2]:
# Comparison of tajectory
import pandas as  pd

df = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\experiments\tracklet_splitter\output\traj_test.csv")
df

,splitter,num_sequences,num_tracklets,mean_purity_macro,mean_purity_weighted,num_true_switches,num_predicted_splits,tp,fp,fn,ids_recall,ids_precision,ids_f1
0,baseline,49.0,2072.0,0.9799,0.985,1048.0,349.0,181.0,168.0,867.0,0.1727,0.5186,0.2591

In [4]:
# Comparison of splitters wo pre-temporalreid-splitting
import pandas as  pd

df = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\experiments\tracklet_splitter\output\comparison_wo_tempreid.csv")
df

,splitter,num_sequences,num_tracklets,mean_purity_macro,mean_purity_weighted,num_true_switches,num_predicted_splits,tp,fp,fn,ids_recall,ids_precision,ids_f1
0,gta,49.0,2367.0,0.9718,0.9699,1048.0,2053.0,290.0,1763.0,758.0,0.2767,0.1413,0.1870
1,temporalreid,49.0,1818.0,0.9736,0.9756,1048.0,93.0,80.0,13.0,968.0,0.0763,0.8602,0.1402
2,jersey,49.0,1734.0,0.9654,0.9617,1048.0,9.0,6.0,3.0,1042.0,0.0057,0.6667,0.0114
3,team,49.0,1805.0,0.9725,0.9746,1048.0,81.0,60.0,21.0,988.0,0.0573,0.7407,0.1063
4,bbox,49.0,1807.0,0.9707,0.9691,1048.0,82.0,47.0,35.0,1001.0,0.0448,0.5732,0.0832
5,trajectory,49.0,1868.0,0.9683,0.9635,1048.0,143.0,46.0,97.0,1002.0,0.0439,0.3217,0.0772
6,jersey+team,49.0,1814.0,0.9731,0.9760,1048.0,90.0,66.0,24.0,982.0,0.0630,0.7333,0.1160
7,jersey+team+bbox,49.0,1880.0,0.9758,0.9799,1048.0,156.0,94.0,62.0,954.0,0.0897,0.6026,0.1561
8,temporalreid+jersey+team+bbox,49.0,1929.0,0.9781,0.9832,1048.0,206.0,134.0,72.0,914.0,0.1279,0.6505,0.2137
9,jersey+team+bbox+temporalreid,49.0,1936.0,0.9780,0.9832,1048.0,212.0,136.0,76.0,912.0,0.1298,0.6415,0.2159
10,jersey+team+bbox+trajectory,49.0,2024.0,0.9779,0.9821,1048.0,300.0,139.0,161.0,909.0,0.1326,0.4633,0.2062

In [ ]:
# Comparison of splitters with pre-temporalreid-splitting
import pandas as  pd

df = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\experiments\tracklet_splitter\output\comparison_w_tempreid.csv")
df

,splitter,num_sequences,num_tracklets,mean_purity_macro,mean_purity_weighted,num_true_switches,num_predicted_splits,tp,fp,fn,ids_recall,ids_precision,ids_f1
0,jersey,49.0,1824.0,0.9741,0.9766,940.0,6.0,4.0,2.0,936.0,0.0043,0.6667,0.0085
1,team,49.0,1871.0,0.9759,0.9804,940.0,55.0,34.0,21.0,906.0,0.0362,0.6182,0.0683
2,bbox,49.0,1875.0,0.9759,0.9787,940.0,57.0,24.0,33.0,916.0,0.0255,0.4211,0.0481
3,trajectory,49.0,1960.0,0.9762,0.9783,940.0,142.0,45.0,97.0,895.0,0.0479,0.3169,0.0832
4,jersey+team,49.0,1877.0,0.9764,0.9814,940.0,61.0,38.0,23.0,902.0,0.0404,0.6230,0.0759
5,jersey+team+bbox,49.0,1930.0,0.9779,0.9832,940.0,114.0,56.0,58.0,884.0,0.0596,0.4912,0.1063
6,jersey+team+bbox+trajectory,49.0,2072.0,0.9799,0.9850,940.0,256.0,101.0,155.0,839.0,0.1074,0.3945,0.1689

:

In [ ]:
# Actual correct values of GTA
import pandas as  pd

df = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\experiments\tracklet_splitter\output\new_gta.csv")
df

,splitter,num_sequences,num_tracklets,mean_purity_macro,mean_purity_weighted,num_true_switches,num_predicted_splits,tp,fp,fn,ids_recall,ids_precision,ids_f1
0,gta,49.0,3776.0,0.9799,0.9721,1048.0,2053.0,290.0,1763.0,758.0,0.2767,0.1413,0.187

In [1]:
# Testing new splitter
import pandas as  pd

df = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\experiments\tracklet_splitter\output\new_traj.csv")
df

,splitter,num_sequences,num_tracklets,mean_purity_macro,mean_purity_weighted,num_true_switches,num_predicted_splits,tp,fp,fn,ids_recall,ids_precision,ids_f1
0,baseline,49.0,1725.0,0.9649,0.9603,1048.0,0.0,0.0,0.0,1048.0,0.0000,NaN,NaN
1,gta,49.0,2367.0,0.9718,0.9699,1048.0,2053.0,155.0,1898.0,893.0,0.1479,0.0755,0.1000
2,temporalreid,49.0,1818.0,0.9736,0.9756,1048.0,93.0,75.0,18.0,973.0,0.0716,0.8065,0.1315
3,jersey,49.0,1734.0,0.9654,0.9617,1048.0,9.0,3.0,6.0,1045.0,0.0029,0.3333,0.0057
4,team,49.0,1805.0,0.9725,0.9746,1048.0,81.0,37.0,44.0,1011.0,0.0353,0.4568,0.0655
5,bbox,49.0,1807.0,0.9707,0.9691,1048.0,82.0,39.0,43.0,1009.0,0.0372,0.4756,0.0690
6,trajectory,49.0,1868.0,0.9683,0.9635,1048.0,143.0,7.0,136.0,1041.0,0.0067,0.0490,0.0118
7,jersey+team,49.0,1814.0,0.9731,0.9760,1048.0,90.0,40.0,50.0,1008.0,0.0382,0.4444,0.0703
8,jersey+team+bbox,49.0,1880.0,0.9758,0.9799,1048.0,156.0,65.0,91.0,983.0,0.0620,0.4167,0.1080
9,temporalreid+jersey+team+bbox,49.0,1929.0,0.9781,0.9832,1048.0,206.0,108.0,98.0,940.0,0.1031,0.5243,0.1722
10,jersey+team+bbox+trajectory,49.0,2024.0,0.9779,0.9821,1048.0,300.0,72.0,228.0,976.0,0.0687,0.2400,0.1068
11,temporalreid_jersey_team_bbox_trajectory,49.0,2071.0,0.9800,0.9851,1048.0,348.0,115.0,233.0,933.0,0.1097,0.3305,0.1648

In [2]:
# Testing new splitter
import pandas as  pd

df = pd.read_csv(r"C:\Users\jelle\Documents\TUEindhoven\Master\Thesis\development\tracklet_splitter_scratch\experiments\tracklet_splitter\output\gta_contiguous.csv")
df

,splitter,num_sequences,num_tracklets,mean_purity_macro,mean_purity_weighted,num_true_switches,num_predicted_splits,tp,fp,fn,ids_recall,ids_precision,ids_f1
0,gta,49.0,3776.0,0.9799,0.9721,1048.0,2053.0,155.0,1898.0,893.0,0.1479,0.0755,0.1